title: WonderWise homepage
description: A place for thoughts and reflection on software developments 
theme: just-the-docs

url: https://vtynhi2001.github.io/wonderwise

aux_links:
  Template Repository: https://github.com/vtynhi2001/wonderwise
